### ISSUE TITLE
Key Error 'wkb' when attempting quickstart

### ISSUE THREAD

**Issue by stfran22** [spatialucr/geosnap#296]
receiving this error when I attempt the first two lines of the quickstart from your site:

  File "C:\Miniconda3\envs\gus5031\lib\site-packages\pandas\core\indexes\base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)

  File "pandas\_libs\index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'wkb'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\tuo27112\OneDrive - Temple University\GIS Programming\Geosnap\geosnap_intro.py", line 9, in <module>
    dc = Community.from_census(state_fips='11')

  File "C:\Miniconda3\envs\gus5031\lib\site-packages\geosnap\_community.py", line 1670, in from_census
    1990: datasets.tracts_1990(states=states),

  File "C:\Miniconda3\envs\gus5031\lib\site-packages\geosnap\_data.py", line 310, in tracts_1990
    return _convert_gdf(t)

  File "C:\Miniconda3\envs\gus5031\lib\site-packages\geosnap\_data.py", line 97, in _convert_gdf
    df["geometry"] = P.map(_deserialize_wkb, df["wkb"])

  File "C:\Miniconda3\envs\gus5031\lib\site-packages\pandas\core\frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)

  File "C:\Miniconda3\envs\gus5031\lib\site-packages\pandas\core\indexes\base.py", line 3082, in get_loc
    raise KeyError(key) from err

KeyError: 'wkb'

**Comment by knaaptime** [comment]
hi, thanks for raising this and sorry for the rough edge. We updated our datasets last week and the machinery got out of sync. I just released version 0.6.0 which should resolve the issue (though i'm leaving this open, so please let us know if it doesnt). If you have all the dependencies installed already, you should be able to update with pip, otherwise the conda release should be finished in a day or so.

**Comment by stfran22** [comment]
Thanks for the quick response. Things are working better now but I’m having another issue viewing the gdf tables created from your “Standardizing Geographic Units Over Time” guide. Will post in GitHub later today.

Best,
Steve
